clc;
clear;

[Crop,Constraints,Weather,Plot] = ...
    loadData_V2();

[BestSol,BestCost] = ...
    CA_HWW_GWO_v3( ...
    Crop,...
    Constraints,...
    Weather,...
    Plot);

[V,D] = evaluateConstraints( ...
        BestSol,...
        Crop,...
        Constraints);

fprintf('\n========================\n');
fprintf('RESOURCE UTILIZATION\n');
fprintf('========================\n');

fprintf('Area Used      = %.2f\n',D.AreaUsed);
fprintf('Water Used     = %.2f\n',D.WaterUsed);
fprintf('Fertilizer Used= %.2f\n',D.FertUsed);
fprintf('Budget Used    = %.2f\n',D.BudgetUsed);

fprintf('\nProfit = %.2f INR\n',BestCost);
%% ==========================================
% Resource Utilization Figure
%% ==========================================

AreaPct = ...
    100*D.AreaUsed/Constraints.AreaMax;

WaterPct = ...
    100*D.WaterUsed/Constraints.WaterMax;

FertPct = ...
    100*D.FertUsed/Constraints.FertMax;

BudgetPct = ...
    100*D.BudgetUsed/Constraints.BudgetMax;

Utilization = [ ...
    AreaPct ...
    WaterPct ...
    FertPct ...
    BudgetPct ];

figure

set(gcf,...
    'Units','centimeters',...
    'Position',[5 5 7 5.72]);

b = bar(Utilization,...
    'FaceColor','w',...
    'LineWidth',1.2);

set(gca,...
    'XTickLabel',...
    {'Area','Water','Fertilizer','Budget'},...
    'FontName','Times New Roman',...
    'FontSize',8,...
    'FontWeight','bold',...
    'LineWidth',1,...
    'Box','on');

ylabel('Utilization (%)',...
    'FontName','Times New Roman',...
    'FontSize',8,...
    'FontWeight','bold');

ylim([0 110])

grid on

print(gcf,...
    'Fig4_ResourceUtilization',...
    '-dpng',...
    '-r600');