clc;
clear;

[Crop,Constraints,Weather,Plot] = ...
    loadData_V2();

[BestSol,BestCost] = ...
    CA_HWW_GWO_v3( ...
    Crop,...
    Constraints,...
    Weather,...
    Plot);

X = reshape(BestSol,3,10);

CropArea = sum(X,2);

CropPercent = ...
    100*CropArea/sum(CropArea);

T = table( ...
    ["Wheat";"Rice";"Mustard"], ...
    CropArea,...
    CropPercent,...
    'VariableNames',...
    {'Crop','Area_ha','Allocation_Percent'});

disp(T)

writetable(T,...
    'OptimalCropAllocation.xlsx');